# Configuration file for training and evaluation

dataset:
  # Options: CUB200, IP102, StanfordDogs
  name: CUB200
  root: ./data/CUB200
  batch_size: 32
  num_workers: 4

model:
  name: resnet50
  pretrained: true

activation:
  # Options: relu, leaky_relu, sigmoid, tanh, moment
  type: relu

training:
  epochs: 20
  learning_rate: 0.001
  weight_decay: 0.0001
  device: cuda

logging:
  save_dir: ./logs
